# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30a3acedd733d9746c018e45a43f80ab3a18fb797e8589d7902c940fd6c860a43881ad624abc45455341e8df593b662ad744a866282b75219ba52c761fd0fe3f

test:
  secret_key_base: 4f6948b77de0638bde07bbf5cc3851ec8ad403983b0d7c49ad8ae8a906921fa26b8c28eff2bb8034681b8a98a7b095138040535d3809c8dda12df9371a19640f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
